networks:
  tomcat-network:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/8

services:
  tomcat32:
    image: loruski/bpd:apache-tomcat-8.0.32
    build: ./tomcat32
    volumes:
      - ./tomcat32/apache-tomcat-8.0.32:/apache-tomcat-8.0.32/
      # - ./tomcat32/logs:/apache-tomcat-8.0.32/logs
    container_name: tomcatBPEL_server
    networks:
      tomcat-network:
        ipv4_address: 20.0.0.10
    ports:
      - 8081:8080 # you may edit the first number, the second one is local to the service
  tomcat511:
    image: loruski/bpd:apache-tomcat-8.5.11
    build: ./tomcat511
    volumes:
      - ./tomcat511/apache-tomcat-8.5.11:/apache-tomcat-8.5.11
    container_name: tomcatWS_server
    networks:
      tomcat-network:
        ipv4_address: 20.0.0.11
    ports:
      - 8082:8080 # you may edit the first number, the second one is local to the service
